
name: .NET Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution: testActions.sln                   # Replace with your solution name, i.e. MyWpfApp.sln.
      PACKAGE_PATH: 'published'                   # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.


    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        include-prerelease: true

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution }} --framework net48

    - name: Build
      run: dotnet build ${{ env.Solution }} --configuration Release --framework net48

    - name: Publish to folder
      run: dotnet publish ${{ env.Solution }} --configuration Release --framework net48 --output ${{ env.PACKAGE_PATH }}

    - name: Create NuGet package
      run: dotnet pack ${{ env.Solution }} --configuration Release --framework net48 --output ${{ env.PACKAGE_PATH }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MyArtifacts
        path: ${{ env.PACKAGE_PATH }}

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"


